#!/system/bin/sh
# Project Raco - Screen Modifier Boot Settings
# This file is automatically generated by the app. Do not edit manually.

# Apply Screen Color Matrix (RGB)
service call SurfaceFlinger 1015 i32 1 f 1.0 f 0 f 0 f 0 f 0 f 1.0 f 0 f 0 f 0 f 0 f 1.0 f 0 f 0 f 0 f 0 f 1

# Apply Screen Saturation
service call SurfaceFlinger 1022 f 1.0